Repository hannesbraun/badenair, pull requests merged in 2020-06, with the labels that each got.

#141 Korrekte Datenbank-Zeitzone
  server/src/main/java/de/hso/badenair/domain/flight/Flight.java
  server/src/main/java/de/hso/badenair/domain/flight/ScheduledFlight.java
  server/src/main/java/de/hso/badenair/domain/schedule/ShiftSchedule.java
  server/src/main/java/de/hso/badenair/domain/schedule/StandbySchedule.java
  server/src/main/java/de/hso/badenair/domain/schedule/Vacation.java
  server/src/main/java/de/hso/badenair/domain/schedule/WorkingHours.java
Labels: bug

#147 Feature/BA-19.10 (Start/Landung)
  frontend-employees/src/app/app.module.ts
  frontend-employees/src/app/components/start-landing/start-landing.component.html
  frontend-employees/src/app/components/start-landing/start-landing.component.scss
  frontend-employees/src/app/components/start-landing/start-landing.component.ts
  frontend-employees/src/app/services/dtos/Dtos.ts
  frontend-employees/src/app/services/flights/flight.service.ts
  server/src/main/java/de/hso/badenair/controller/dto/flight/TrackingDto.java
  server/src/main/java/de/hso/badenair/controller/flight/FlightController.java
  server/src/main/java/de/hso/badenair/domain/flight/Flight.java
  server/src/main/java/de/hso/badenair/domain/flight/FlightAction.java
  server/src/main/java/de/hso/badenair/service/flight/FlightService.java
  server/src/main/java/de/hso/badenair/service/flight/repository/FlightCrewMemberRepository.java
Labels: feature

#142 Keine vergangenen Flüge hinzufügen
  server/src/main/java/de/hso/badenair/util/init/StaticDataInitializer.java
Labels: enhancement

#151 BA-19.6 Schichtplan & Bereitschaftsdienstplan
  frontend-employees/src/app/pages/shift-schedule-page/shift-schedule-page.component.html
  frontend-employees/src/app/services/service-schedule/service-schedule.service.ts
  server/src/main/java/de/hso/badenair/controller/dto/plan/StandbyDto.java
  server/src/main/java/de/hso/badenair/controller/plan/PlanController.java
  server/src/main/java/de/hso/badenair/domain/flight/ScheduledFlight.java
  server/src/main/java/de/hso/badenair/domain/schedule/Vacation.java
  server/src/main/java/de/hso/badenair/service/flight/repository/FlightCrewMemberRepository.java
  server/src/main/java/de/hso/badenair/service/flight/repository/FlightRepository.java
  server/src/main/java/de/hso/badenair/service/flight/repository/ScheduledFlightRepository.java
  server/src/main/java/de/hso/badenair/util/init/CrewData.java
  server/src/main/java/de/hso/badenair/util/init/FlightGroup.java
  server/src/main/java/de/hso/badenair/util/init/StaticDataInitializer.java
Labels: feature

#163 Buchungen in den letzten 45 Minuten vor Abflug
  server/src/main/java/de/hso/badenair/service/flight/booking/BookingService.java
Labels: bug

#164 Wartungs-Button & weiteres
  frontend-employees/src/app/components/plane-maintenance/plane-maintenance.component.html
  frontend-employees/src/app/components/plane-maintenance/plane-maintenance.component.ts
  frontend-employees/src/app/components/start-landing/start-landing.component.html
  frontend-employees/src/app/components/start-landing/start-landing.component.ts
  frontend-employees/src/app/services/dtos/Dtos.ts
  frontend-employees/src/app/services/flights/flight.service.ts
  server/src/main/java/de/hso/badenair/controller/dto/maintenance/PlaneMaintenanceDto.java
  server/src/main/java/de/hso/badenair/controller/flight/FlightController.java
  server/src/main/java/de/hso/badenair/domain/plane/Plane.java
  server/src/main/java/de/hso/badenair/service/flight/FlightService.java
  server/src/main/java/de/hso/badenair/util/init/StaticDataInitializer.java
  server/src/main/java/de/hso/badenair/util/mapper/PlaneMapper.java
Labels: enhancement, feature

#166 Änderungen am Schicht- und Bereitschaftsdienstplan
  server/src/main/java/de/hso/badenair/domain/flight/ScheduledFlight.java
  server/src/main/java/de/hso/badenair/service/flight/FlightService.java
  server/src/main/java/de/hso/badenair/service/plan/PlanService.java
  server/src/main/java/de/hso/badenair/service/plan/shift/ShiftPlanService.java
  server/src/main/java/de/hso/badenair/util/init/CrewData.java
  server/src/main/java/de/hso/badenair/util/init/StaticDataInitializer.java
Labels: bug, enhancement
