Repository hannesbraun/badenair, pull requests merged in 2020-05, with the labels that each got.

#109 Feature/BA-15.14 Gebuchte Flüge (Frontend)
  frontend-customers/src/app/components/booked-flights/booked-flights.component.html
  frontend-customers/src/app/components/booked-flights/booked-flights.component.ts
  frontend-customers/src/app/components/flight/flight.component.ts
  frontend-customers/src/app/services/account/account.service.ts
Labels: feature

#107 Sitzplatzauswahl
  frontend-customers/src/app/app-routing.module.ts
  frontend-customers/src/app/app.module.ts
  frontend-customers/src/app/components/booking-overview/booking-overview.component.html
  frontend-customers/src/app/components/flight-search/flight-search.component.html
  frontend-customers/src/app/components/flight/flight.component.html
  frontend-customers/src/app/components/flight/flight.component.ts
  frontend-customers/src/app/components/navigation/navigation.component.html
  frontend-customers/src/app/components/navigation/navigation.component.scss
  frontend-customers/src/app/components/passengers-form/passengers-form.component.html
  frontend-customers/src/app/components/passengers-form/passengers-form.component.ts
  frontend-customers/src/app/components/seat-selection/seat-selection.component.html
  frontend-customers/src/app/components/seat-selection/seat-selection.component.scss
  frontend-customers/src/app/components/seat-selection/seat-selection.component.spec.ts
  frontend-customers/src/app/components/seat-selection/seat-selection.component.ts
  frontend-customers/src/app/pages/booking-overview-page/booking-overview-page.component.html
  frontend-customers/src/app/pages/booking-overview-page/booking-overview-page.component.ts
  frontend-customers/src/app/pages/flights-page/flights-page.component.html
  frontend-customers/src/app/pages/flights-page/flights-page.component.ts
  frontend-customers/src/app/pages/passengers-page/passengers-page.component.html
  frontend-customers/src/app/pages/passengers-page/passengers-page.component.scss
  frontend-customers/src/app/pages/passengers-page/passengers-page.component.spec.ts
  frontend-customers/src/app/pages/passengers-page/passengers-page.component.ts
  frontend-customers/src/app/pages/seat-selection-page/seat-selection-page.component.html
  frontend-customers/src/app/pages/seat-selection-page/seat-selection-page.component.scss
  frontend-customers/src/app/pages/seat-selection-page/seat-selection-page.component.spec.ts
  frontend-customers/src/app/pages/seat-selection-page/seat-selection-page.component.ts
  frontend-customers/src/app/services/dtos/Dtos.ts
  frontend-customers/src/app/services/search/booking-state.service.ts
  frontend-customers/src/app/services/seat/seat.service.spec.ts
  frontend-customers/src/app/services/seat/seat.service.ts
  frontend-customers/src/assets/bg.jpg
  frontend-customers/src/assets/logo.png
  frontend-customers/src/styles.scss
  server/src/main/java/de/hso/badenair/controller/dto/seat/SeatDto.java
  server/src/main/java/de/hso/badenair/controller/seat/SeatController.java
  server/src/main/java/de/hso/badenair/domain/plane/PlaneTypeData.java
  server/src/main/java/de/hso/badenair/service/seat/SeatService.java
  server/src/main/java/de/hso/badenair/util/init/StaticDataInitializer.java
  server/src/main/resources/data.sql
Labels: feature

#112 Feature/BA-19.5 Flugsuche
  frontend-customers/src/app/pages/flight-search-page/flight-search-page.component.ts
  frontend-customers/src/app/pages/flights-page/flights-page.component.html
  frontend-customers/src/app/pages/flights-page/flights-page.component.scss
  frontend-customers/src/app/pages/flights-page/flights-page.component.ts
  server/src/main/java/de/hso/badenair/controller/flight/search/FlightSearchController.java
  server/src/main/java/de/hso/badenair/service/flight/search/FlightSearchService.java
Labels: feature

#95 Flugzeuge, Flughäfen und Flugplan hinzufügen
  server/src/main/java/de/hso/badenair/domain/plane/PlaneType.java
  server/src/main/java/de/hso/badenair/service/airport/AirportRepository.java
  server/src/main/java/de/hso/badenair/service/flight/repository/ScheduledFlightRepository.java
  server/src/main/java/de/hso/badenair/service/plane/repository/PlaneRepository.java
  server/src/main/java/de/hso/badenair/util/csv/CsvHelper.java
  server/src/main/java/de/hso/badenair/util/init/StaticDataInitializer.java
  server/src/main/resources/data.sql
  server/src/main/resources/data/airports.csv
  server/src/main/resources/data/flightplan.csv
  server/src/main/resources/data/flightplanDemo.csv
  server/src/test/java/de/hso/badenair/controller/BoardingPassControllerTest.java
Labels: feature

#122 Feature/BA-19.2 Flugpreise & weitere kleine Fixes
  frontend-customers/src/app/components/booking-overview/booking-overview.component.html
  frontend-customers/src/app/components/booking-overview/booking-overview.component.ts
  frontend-customers/src/app/components/flight/flight-info/flight-info.component.ts
  frontend-customers/src/app/components/flight/flight.component.html
  frontend-customers/src/app/components/passengers-form/passengers-form.component.html
  frontend-customers/src/app/components/passengers-form/passengers-form.component.ts
  frontend-customers/src/app/pages/booking-overview-page/booking-overview-page.component.html
  frontend-customers/src/app/pages/booking-overview-page/booking-overview-page.component.ts
  frontend-customers/src/app/pages/check-in-page/check-in-page.component.html
  frontend-customers/src/app/pages/success-page/success-page.component.html
  server/pom.xml
  server/src/main/java/de/hso/badenair/controller/account/AccountController.java
  server/src/main/java/de/hso/badenair/controller/flight/PriceCalculator.java
  server/src/main/java/de/hso/badenair/service/account/AccountService.java
  server/src/main/java/de/hso/badenair/service/flight/booking/BookingService.java
Labels: enhancement, feature

#132 Bugfix/sitzplätze
  frontend-customers/src/app/components/booking-overview/booking-overview.component.scss
  frontend-customers/src/app/components/seat-selection/seat-selection.component.ts
  frontend-customers/src/app/pages/booking-overview-page/booking-overview-page.component.html
  frontend-customers/src/app/pages/booking-overview-page/booking-overview-page.component.ts
  frontend-customers/src/app/services/info/info.service.ts
  frontend-customers/src/styles.scss
  server/src/main/java/de/hso/badenair/service/flight/booking/BookingService.java
  server/src/main/java/de/hso/badenair/service/seat/SeatService.java
Labels: bug
